export const enum AuthServiceToken {
  AUTH_SERVICE = "AUTH_SERVICE",
}

export const enum AuthCommandToken {
  LOGIN_USER_COMMAND = "LOGIN_USER_COMMAND",
  REFRESH_TOKEN_COMMAND = "REFRESH_TOKEN_COMMAND",
  RESET_SESSION_COMMAND = "RESET_SESSION_COMMAND",
}
