export const enum TaskRepositoryToken {
  TASK_REPOSITORY = "TASK_REPOSITORY",
}

export const enum TaskCommandToken {
  CREATE_TASK_COMMAND = "CREATE_TASK_COMMAND",
  UPDATE_TASK_COMMAND = "UPDATE_TASK_COMMAND",
  DELETE_TASK_COMMAND = "DELETE_TASK_COMMAND",
  CHANGE_TASK_LIST_COMMAND = "CHANGE_TASK_LIST_COMMAND",
}

export const enum TaskQueryToken {
  GET_TASK_QUERY = "GET_TASK_QUERY",
  GET_TASKS_QUERY = "GET_TASKS_QUERY",
}
