export const enum ListRepositoryToken {
  LISTS_REPOSITORY = "LISTS_REPOSITORY",
}

export const enum ListCommandToken {
  CREATE_LIST_COMMAND = "CREATE_LIST_COMMAND",
  UPDATE_LIST_COMMAND = "UPDATE_LIST_COMMAND",
  DELETE_LIST_COMMAND = "DELETE_LIST_COMMAND",
}

export const enum ListQueryToken {
  GET_LIST_QUERY = "GET_LIST_QUERY",
  GET_LISTS_QUERY = "GET_LISTS_QUERY",
}
